### ISSUE TITLE
Error traducción

### ISSUE THREAD

**Issue by danielchc** [BadWolf-alfa/MIUIPRO-MIUI10-SPANISH#1]
https://github.com/BadWolf-alfa/MIUIPRO-MIUI10-SPANISH/blob/155b6710f83f01ef08a7c12204834cd297c9ea6d/Spanish/main/SecurityCenter.apk/res/values-es/strings.xml#L910

![image](https://user-images.githubusercontent.com/33174848/42382149-a86d2b8e-8133-11e8-8611-3b3e48d79b20.png)

**Comment by BadWolf-alfa** [comment]
Arreglado en la actualización de hoy / Fixed in the last update
